server:
  port: 9098
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka-one:5001/eureka
spring:
  application:
    name: school-service
logging:
  level:
    com.example.howtodoinjava: DEBUG