server:
  port: 8098
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-one:5001/eureka
management:
  security:
    enabled: false
logging:
  level:
    com.example.howtodoinjava: DEBUG