spring:
  profiles: default
server:
  port: 5001
eureka:
  dashboard:
    enabled: true
  instance:
    appname: ${spring.application.name}
    hostname: eureka-one
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-two:5002/eureka,http://eureka-three:5003/eureka
---
spring:
  profiles: cloud
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: ${vcap.services.user-provided-service.credentials.eureka-server-two-mi} 